
CREATE TABLE NhanVien (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    HoTen NVARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20) NOT NULL,
    ChucVu NVARCHAR(50)
);
GO

CREATE TABLE Xe (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    SoKhungSoMay VARCHAR(50) UNIQUE NOT NULL,
    HangXe NVARCHAR(50) NOT NULL,
    DongXe NVARCHAR(50) NOT NULL,
    GiaBan DECIMAL(18, 2) NOT NULL,
    DaBan BIT DEFAULT 0
);
GO

CREATE TABLE HinhAnhXe (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    XeId INT NOT NULL,
    DuongDanAnh NVARCHAR(500) NOT NULL,
    LaAnhChinh BIT DEFAULT 0,
    
    CONSTRAINT FK_HinhAnhXe_Xe FOREIGN KEY (XeId) REFERENCES Xe(Id) ON DELETE CASCADE
);
GO

CREATE TABLE DonHang (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    NgayLap DATETIME DEFAULT GETDATE(),
    GiaChot DECIMAL(18, 2) NOT NULL,
    
    NhanVienId INT NOT NULL,
    XeId INT NOT NULL UNIQUE,

    CONSTRAINT FK_DonHang_NhanVien FOREIGN KEY (NhanVienId) REFERENCES NhanVien(Id),
    CONSTRAINT FK_DonHang_Xe FOREIGN KEY (XeId) REFERENCES Xe(Id)
);
GO
